TEAMSchools/teamster

teamster/core/config/datagun/query-sftp-test.yaml
teamster/core/ops/datagun.py
teamster/local/config/powerschool/db/query-incremental.yaml

- checkout
- checkout
- fix stg
- change today

stg kippnewark

---

requirements.txt

Reverts TEAMSchools/teamster#46

Revert "Bump grpcio-status from 1.47.2 to 1.50.0"

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

adding text box values with regex to remove html tags

Text boxes

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

Adding row numbers

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__student_misc.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__transcript_gpas.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__transcript_grades.sql

Deanslist extracts

---

src/dbt/iready/models/staging/stg_iready__diagnostic_results.sql
src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql
src/dbt/kipptaf/models/iready/staging/stg_iready__diagnostic_results.sql

Gradebook dash troubleshoot

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/kippadb/staging/stg_kippadb__contact_note.sql

Kwfd tier regex

---

src/dbt/kipptaf/models/assessments/sources.yml
src/dbt/kipptaf/models/assessments/staging/src_assessments__academic_goals.sql
src/dbt/kipptaf/models/assessments/staging/src_assessments__act_scale_score_key.sql
src/dbt/kipptaf/models/assessments/staging/src_assessments__qbls_power_standards.sql

new tables

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Kfwd scaffold

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

Coach matching

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

adjusting the join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_goals.sql

adding microgoal scaffold

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_goals.sql

fix to remove additional tags

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__reading_levels.sql

added new table with descriptions for verbiage

---

.trunk/trunk.yaml
src/teamster/kipptaf/datagun/config/deanslist.yaml

add extracts

---

src/dbt/kipptaf/models/extracts/powerschool/rpt_powerschool__autocomm_teachers.sql

Teachers autocomm update

---

src/dbt/kipptaf/models/amplify/staging/stg_amplify__benchmark_student_summary.sql
src/dbt/kipptaf/models/assessments/intermediate/int_assessments__scaffold.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__iready_diagnostics.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__mod_assessment.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__mod_standards.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__reading_levels.sql

filters and tweaks

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql

fix deduplicate partition

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition.sql
src/dbt/kipptaf/models/people/intermediate/int_people__years_experience.sql

1. Correcting years_exp so that it counts NULL job historic titles
2. Creating an annual adjustment for years_exp (so that historic years exp show up as the experience a person had for that year)
[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205492080945304

Attrition years correction

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__reading_levels.sql

Changed Not Enough Data on Q1 to Not applicable

---

src/dbt/kipptaf/models/assessments/sources.yml
src/dbt/kipptaf/models/assessments/staging/stg_assessments__standard_domains.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__mod_standards_domains.sql

std domains

---

src/dbt/kipptaf/models/people/staging/stg_people__student_logins.sql

limit last name to 18 chars

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql

fix yearid join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

change to FAST sublevel join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205530398743325

Grad requirements iep portfolio

---

src/dbt/kipptaf/models/assessments/sources.yml
src/dbt/kipptaf/models/assessments/staging/stg_assessments__state_test_comparison.sql

state test comp sheet

---

src/dbt/kipptaf/models/adp_workforce_manager/intermediate/int_adp_workforce_manager__accrual_summary_pivot.sql
src/dbt/kipptaf/models/adp_workforce_manager/staging/stg_adp_workforce_manager__accrual_reporting_period_summary.sql
src/dbt/kipptaf/models/adp_workforce_manager/staging/stg_adp_workforce_manager__time_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attendance.sql

Staff attendance

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205560385751312

Transition i-Ready APM view to dbt/BQ

---

src/dbt/kipptaf/models/kippadb/staging/stg_kippadb__gpa.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205604423828777

Add December to fall transcript window

---

src/dbt/kipptaf/models/reporting/staging/stg_reporting__terms.sql

add bit about past years

---

src/dbt/titan/models/staging/stg_titan__income_form_data.sql

reclassify njeie

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205640747516851

Grad reqs refactor

---

src/dbt/iready/models/staging/stg_iready__instructional_usage_data.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/snapshots/iready/snapshot_iready__instructional_usage_data.sql

Iready usage snapshot

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

switched source of time-on-task metric to snapshot view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__student_info_audit.sql
src/dbt/kipptaf/models/powerschool/qa/qa_powerschool__course_enrollment_overlap.sql

Data quality dashboard

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205702540950830

updated with new promo reporting view

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205702540950835

add credit requirements

---

src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__attendance_streak.sql
src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippmiami.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/powerschool/models/intermediate/int_powerschool__attendance_streak.sql

closes #341 
[^1]:
dependencies.

add models

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205733130709900

NULL value for current i-Ready

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__iready_lessons.sql

[^1]:
dependencies.
---
- https://app.asana.com/0/0/1205733130709905

remove "distinct" from count of lessons

---

src/dbt/kipptaf/models/dayforce/base/base_dayforce__employee_history.sql
src/dbt/kipptaf/models/people/base/base_people__staff_roster_history.sql

Fix prestart filter

---

src/dbt/kipptaf/models/assessments/intermediate/int_assessments__course_enrollments.sql

add date enrolled to dedupe partition

---

src/dbt/kipptaf/models/assessments/intermediate/int_assessments__scaffold.sql

Assessments course enr fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

Iready filter add

---

.devcontainer/devcontainer.json
pdm.lock
pyproject.toml
src/teamster/kippcamden/Dockerfile
src/teamster/kippmiami/Dockerfile
src/teamster/kippnewark/Dockerfile
src/teamster/kipptaf/Dockerfile
src/teamster/staging/Dockerfile

update deps, refs to 3.10

---

src/dbt/kipptaf/models/assessments/base/base_assessments__assessments.sql
src/dbt/kipptaf/models/assessments/intermediate/int_assessments__scaffold.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__assessment_tag_audit.sql
src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__assessment_fields.sql
src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__field_standards.sql
src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__fields_reporting_groups.sql
src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__grade_levels.sql

add/refactor models, port audit

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

added grad calcs to gpa bands

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__persistence.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql

add persistence view

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

Update NJ promo criteria

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

fixing all the current problems

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

Matching current bootleg version

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

adding is_grad_ever to dash

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_job_salary_audit.sql

- [ x] <kbd>Format</kbd> has been run on all requested files
---
- https://app.asana.com/0/0/1205886629696296

creating new table for tableau view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

added ktx_cohort to final select statement

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

---
- https://app.asana.com/0/0/1205913247305115

hotfix for HS overall promo status

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

ecc_avg_mins

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

hotfix: HS attendance info

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__mod_standards_domains.sql

standards-hotfix

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

---
- https://app.asana.com/0/0/1205951808270994

data source for flc

---

src/dbt/kipptaf/models/surveys/intermediate/int_surveys__support_survey_details.sql

Only allowing rn=1 submissions and removing the respondent name
- [x ] Create a Pull Request task on our
- [x ] <kbd>Format</kbd> has been run on all requested files
---
- https://app.asana.com/0/0/1205940660933643

Support survey rn fix & removing respondent name question

---

src/dbt/kipptaf/models/surveys/intermediate/int_surveys__manager_survey_details.sql
src/dbt/kipptaf/models/surveys/staging/stg_surveys__manager_survey_detail_archive.sql

creating the survey detail model for manager surveys
- [ x] Create a Pull Request task on our
- [x ] <kbd>Format</kbd> has been run on all requested files
---
- https://app.asana.com/0/0/1205940660933648

manager survey detail model

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql

round need_60

---

src/teamster/core/achieve3k/sensors.py
src/teamster/core/adp/sensors.py
src/teamster/core/clever/sensors.py
src/teamster/core/datagun/assets.py
src/teamster/core/edplan/sensors.py
src/teamster/core/iready/sensors.py
src/teamster/core/powerschool/assets.py
src/teamster/core/powerschool/schedules.py
src/teamster/core/powerschool/sensors.py
src/teamster/core/renlearn/sensors.py
src/teamster/core/sftp/assets.py
src/teamster/core/ssh/resources.py
src/teamster/core/titan/sensors.py
src/teamster/kippcamden/definitions.py
src/teamster/kippmiami/definitions.py
src/teamster/kippnewark/definitions.py
src/teamster/kipptaf/definitions.py
src/teamster/staging/definitions.py
tests/powerschool/test_powerschool_resources.py
tests/powerschool/test_powerschool_schedules.py
tests/powerschool/test_powerschool_sensor.py
tests/sftp/test_sftp_assets.py
tests/sftp/test_sftp_resource.py
tests/sftp/test_sftp_sensors.py

Dagster ssh resource

---

src/dbt/kipptaf/models/pearson/intermediate/int_pearson__all_assessments.sql

---
- https://app.asana.com/0/0/1205996994247994

add rn_highest_student_test

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__persistence.sql

[//]: # fix is_ecc calc which is returning false positives
---
- https://app.asana.com/0/0/1206057762363952

hotfix for is_ecc calc

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__assessment_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__power_standards.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__qbl.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

[//]: # Create power standards tableau view
---
- https://app.asana.com/0/0/1206052081292734

Create power standards Tableau view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

adding username & report to username to the view

adding mail + report_to_mail

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

…i-Ready
[//]: Add course teachers & sections

SL requested additions for i-Ready APM

---

src/dbt/kipptaf/models/assessments/sources.yml

---
- https://app.asana.com/0/0/1206073229865905

add gsheet

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

Reverts TEAMSchools/teamster#425

Revert "Smg tier adjustment"

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

Smg tier adjustment

---

src/teamster/core/adp/workforce_manager/assets.py
src/teamster/core/alchemer/assets.py
src/teamster/core/amplify/assets.py
src/teamster/core/datagun/assets.py
src/teamster/core/dbt/assets.py
src/teamster/core/deanslist/assets.py
src/teamster/core/google/directory/assets.py
src/teamster/core/google/forms/assets.py
src/teamster/core/google/sheets/assets.py
src/teamster/core/iready/assets.py
src/teamster/core/ldap/assets.py
src/teamster/core/powerschool/assets.py
src/teamster/core/schoolmint/grow/assets.py
src/teamster/core/smartrecruiters/assets.py
src/teamster/core/titan/assets.py

initial remove

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

Allowing for forms with missing overall scores, and also allowing for forms that should not have overall scores (eg: walkthrough and personal reflection)

removing overall_score thingy

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ops_dashboard.sql

add school abbrev. to ops dash

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_persistence.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__persistence.sql

---
- https://app.asana.com/0/0/1206096015298829

persistence updates

---

src/dbt/kippmiami/models/fldoe/staging/stg_fldoe__fsa.sql

---
- https://app.asana.com/0/0/1206105245202564

Add perf levels and prof label to fsa

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

the tier 1 calculation was wrong, resulting in some folks getting a null tier

updating the SO tier 1 range

---

src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__grants_timesheets.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__response_identifiers.sql

---
- https://app.asana.com/0/0/1206114700424336

444 survey response identifiers are null not matching to roster info

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__student_misc.sql

---
- https://app.asana.com/0/0/1206114334518390

add principal name & phone to student_misc for suspension letters

---

src/teamster/kipptaf/schoolmint/grow/schema.py
tests/assets/test_schoolmint_grow_assets.py

fix schema

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__sight_words_dashboard.sql

---
- https://app.asana.com/0/0/1206122428035720

Nj filter to sight words

---

src/dbt/kipptaf/models/assessments/intermediate/int_assessments__course_enrollments.sql

fix partition

---

src/dbt/kipptaf/models/assessments/staging/stg_assessments__college_readiness_expected_tests.sql

---
- https://app.asana.com/0/0/1206124558002531

create stg for carat expected tests

---

src/teamster/core/dbt/assets.py
src/teamster/kipptaf/dbt/assets.py

460 fix dagster asset group on dbt assets

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__iready_diagnostics.sql
src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql

[//]: add i-Ready overall placement for new DL report
---
- https://app.asana.com/0/0/1206146937821250

add i-Ready overall placement for new DL report

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__qbl.sql

fixed term join

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

---
- https://app.asana.com/0/0/1206183858708538

add LEP status to flc gsheet

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

---
- https://app.asana.com/0/0/1206183422219131

add i-Ready exclusion lists to filters, view

---

src/dbt/kipptaf/models/deanslist/staging/stg_deanslist__reconcile_attendance.sql
src/dbt/kipptaf/models/deanslist/staging/stg_deanslist__reconcile_suspensions.sql

staging models
---
- https://app.asana.com/0/0/1206207019477597

feat: dl recon stg models

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

---
- https://app.asana.com/0/0/1206207630808479

adding new questions to pivot

---

.trunk/trunk.yaml
src/teamster/kipptaf/amplify/schema.py
tests/assets/test_amplify_assets.py

fix: schema

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__assessment_dashboard.sql

additional cohort fields to assessment dashboard tableau view

---

.trunk/trunk.yaml
pyproject.toml
src/dbt/powerschool/models/base/base_powerschool__final_grades.sql
src/dbt/powerschool/models/base/base_powerschool__sections.sql
src/dbt/powerschool/models/intermediate/int_powerschool__category_grades.sql
src/dbt/powerschool/models/staging/stg_powerschool__pgfinalgrades.sql
src/dbt/powerschool/models/staging/stg_powerschool__storedgrades.sql

- closes #512 and #519 
- refactor cte calcs to staging tables
---
- https://app.asana.com/0/0/1206276393184866

fix: need to get calcs

---

src/teamster/kipptaf/fivetran/sensors.py
src/teamster/staging/definitions.py
src/teamster/staging/resources.py
tests/sensors/test_fivetran_sensor.py

---
- https://app.asana.com/0/0/1206288742378376

521 optimize fivetran log query

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__promo_status.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

Promo status - HS updates per NJ

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

---
- https://app.asana.com/0/0/1206305849720179

NJ promo: correcting a mistake from previous pull req

---

src/dbt/kipptaf/models/extracts/rpt_coupa__users.sql

fix: remove Leave deactivations

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

First pass add ap to carat

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

Reverts TEAMSchools/teamster#539

Revert "First pass add ap to carat"

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

fixing the issue where it would only join if someone had an observation

---

.vscode/settings.json
src/dbt/powerschool/models/sources.yml
src/teamster/core/resources.py
src/teamster/kippcamden/powerschool/config/assets-nonpartition.yaml
src/teamster/kippmiami/powerschool/config/assets-nonpartition.yaml
src/teamster/kippnewark/powerschool/config/assets-nonpartition.yaml
tests/assets/test_powerschool_assets.py

---
- https://app.asana.com/0/0/1206413397188026

feat: add tables

---

src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippmiami.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/kipptaf/models/powerschool/staging/stg_powerschool__studenttest.sql
src/dbt/kipptaf/models/powerschool/staging/stg_powerschool__studenttestscore.sql
src/dbt/powerschool/models/staging/stg_powerschool__studenttest.sql
src/dbt/powerschool/models/staging/stg_powerschool__studenttestscore.sql

535 bring over custom test score data

---

src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__ada.sql
src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippmiami.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/powerschool/models/intermediate/int_powerschool__ada.sql

---
- https://app.asana.com/0/0/1206446093298941

refactor: mv ada to powerschool package

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql

fixing count problems on year_at_kipp
---
- https://app.asana.com/0/0/1206444881482731

Fixing year at kipp count

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

fix regex for subject

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__assessment_dashboard.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

---
- https://app.asana.com/0/0/1206455183830694

Assessment join fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__suspension_over_time.sql

---
- https://app.asana.com/0/0/1206471130229640

create Tableau suspension over time view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

add ugrad status

---

pdm.lock
pyproject.toml
src/teamster/core/google/storage/io_manager.py
src/teamster/core/ssh/resources.py
src/teamster/kipptaf/adp/payroll/assets.py
src/teamster/kipptaf/adp/payroll/schema.py
src/teamster/kipptaf/adp/payroll/sensors.py
tests/assets/test_sftp_assets.py
tests/sensors/test_sftp_sensors.py

---
- https://app.asana.com/0/0/1206481026877732

feat: adp payroll asset and sensor

---

src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/adp_payroll/sources.yml
src/dbt/kipptaf/models/adp_payroll/staging/stg_adp_payroll__general_ledger_file.sql

feat: staging model

---

src/dbt/kipptaf/models/finance/sources.yml
src/dbt/kipptaf/models/finance/staging/stg_finance__payroll_code_mapping.sql
src/dbt/kipptaf/models/people/sources.yml
src/dbt/kipptaf/models/people/staging/stg_people__salary_scale.sql

feat: add sheets

---

src/dbt/kippcamden/models/extracts/powerschool/rpt_powerschool__autocomm_teachers.sql
src/dbt/kippmiami/models/extracts/powerschool/rpt_powerschool__autocomm_teachers.sql
src/dbt/kippnewark/models/extracts/powerschool/rpt_powerschool__autocomm_teachers.sql

---
- https://app.asana.com/0/0/1206489992892909

fix: add missing col

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql
src/dbt/kipptaf/models/kippadb/base/base_kippadb__application.sql

add UNION to include app/acceptance data

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__student_misc.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

Application data source column + deanslist add

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

fix join, add demo fields

---

.devcontainer/devcontainer.json
.github/workflows/dagster-cloud-deploy.yaml
.github/workflows/deploy-branch-staging.yaml
.k8s/dagster/values-override.yaml
Dockerfile
pdm.lock
pyproject.toml
src/teamster/staging/dagster-cloud-staging.yaml
src/teamster/staging/definitions.py

feat: multi arch build

---

src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql

fix: remove order by clause in window calcs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__zendesk_tickets.sql

fix: lowercase email on join

---

src/dbt/deanslist/models/intermediate/int_deanslist__incidents__custom_fields__pivot.sql

---
- https://app.asana.com/0/0/1206538323521414

Update dl custom pivot

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_responses.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__survey_responses.sql

Fix double-counting of entity changers and people with more than one active position during a time period and add adp status to the tableau
---
- https://app.asana.com/0/0/1206489739769073

Term records fix

---

src/dbt/kipptaf/models/surveys/intermediate/int_surveys__survey_responses.sql

Adding rn curr filter to google forms submissions
---
- https://app.asana.com/0/0/1206556286462075

adding rn curr

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

spelling error, whoops! add two fields

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

Contact note update

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__nj_state_test_roster.sql

create NJ test roster

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__intact_integration_file.sql

Setting up the intacct file for the accounting team to pull into their systems
quick note on sqlfluff - the order of the columns matters for accounting, so I ignored a few sqlfluff rules in order to keep everything in the right place
Allow me to create a clean gsheet that will manage the things for accounting
---
- To see the specific tasks where the Asana app for GitHub is being …

setting up view for gsheet

---

src/dbt/kipptaf/models/people/intermediate/int_people__expected_next_year_salary.sql

The tool is assigning the wrong salary to Learning Specialists
Correct the typo on Learrning Specialist
---
- https://app.asana.com/0/0/1206672097193771

correcting typo

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_audit.sql

create qbl/power standard audit view

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__nj_state_test_roster.sql

add session name calc field

---

pdm.lock
pyproject.toml
src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippmiami.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/kipptaf/models/powerschool/staging/stg_powerschool__sced_code_mapping.sql
src/dbt/powerschool/models/staging/stg_powerschool__sced_code_mapping.sql

---
- https://app.asana.com/0/0/1206698126347863

536 add a tag for ap courses to show they are ap and their crdc grouping

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

ECC-Acceptances. Smile and wave boys, smile and wave.

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

fix operator

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

added_dbt_relation

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

added_new_int_table

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

Added dlm field

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

Golf Papa Alpha Updates

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__intact_integration_file.sql

They need some column headers changed
---
- https://app.asana.com/0/0/1206753964863845

updating column headers

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

---
- https://app.asana.com/0/0/1206755331925711

fix enrollments on career

---

src/dbt/powerschool/models/base/base_powerschool__course_enrollments.sql

fix: dropped section using max calendardate

---

src/dbt/kipptaf/models/students/intermediate/int_students__fldoe_fte.sql

---
- https://app.asana.com/0/0/1206790117949113

feat: fldoe fte view

---

src/dbt/kippcamden/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kippnewark/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kipptaf/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kipptaf/models/students/intermediate/int_students__graduation_path_codes.sql

---
- https://app.asana.com/0/0/1206789744010862

Autocomm grad pathway

---

Dockerfile
src/dbt/kipptaf/models/alchemer/sources.yml
src/dbt/kipptaf/models/alchemer/staging/stg_alchemer__survey_response_disqualified.sql
src/teamster/kipptaf/alchemer/assets.py
src/teamster/kipptaf/alchemer/schema.py
src/teamster/kipptaf/alchemer/sensors.py
tests/assets/test_alchemer_assets.py

feat: add dq responses

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__ddi_tier_roster.sql

Gsheet buckets

---

src/dbt/kipptaf/models/alchemer/staging/stg_alchemer__survey_response.sql
src/dbt/kipptaf/models/alchemer/staging/stg_alchemer__survey_response_disqualified.sql
src/teamster/kipptaf/resources.py

feat: add dq filter;fix: increase timeout

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

Spi gradrate update

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__ddi_tier_roster.sql

add region, update column names

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

Miami FAST dashboard updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__approved_home_instruction.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__home_instruction_queue.sql

migrate home instruction queue to BQ/dbt

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

add gpa bands to junior view

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

add EA/ED flag to tracker view

---

src/dbt/kipptaf/models/amplify/staging/stg_amplify__benchmark_student_summary.sql

feat: use T/O Discont for lvl

---

src/dbt/kipptaf/models/schoolmint/grow/staging/stg_schoolmint_grow__observations_history.sql
src/dbt/kipptaf/models/schoolmint/grow/staging/stg_schoolmint_grow__observations_history__observation_scores.sql

fix: add end date

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

fix es enrollment issue

---

src/dbt/kipptaf/models/extracts/rpt_coupa__users.sql

feat: disable purchasing for leave

---

.github/workflows/dagster-cloud-deploy.yaml
Dockerfile
src/dbt/kipptaf/models/assessments/sources.yml
src/dbt/kipptaf/models/assessments/staging/stg_assessments__ap_course_crosswalk.sql

---
- https://app.asana.com/0/0/1206836120309178

749 new ap course codes to adb ap score subjects crosswalk

---

src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__psat.sql

they all float

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

Add psat 2023 to early warning

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__njsmart_transfer_unverified.sql

create TO-Unverified gsheet roster for compliance team

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__suspension_over_time.sql

add incidents count running

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__community_service.sql

migrate community service tableau view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

hotfix: missing WHERE in Miami FAST cte

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_matriculation.sql

Create new collab matric

---

Dockerfile
src/dbt/kipptaf/models/extracts/properties.yml
src/teamster/core/dbt/assets.py

488 consider implementing freshness policies

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

Miami update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

add fldoe growth calc

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_dashboard.sql
src/dbt/powerschool/models/base/base_powerschool__final_grades.sql

refactor: final grades cte

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_chronic_absenteeism_log.sql

---
- https://app.asana.com/0/0/1206935475621176

feat: add model

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__school_culture_dashboard_nj.sql

---
- https://app.asana.com/0/0/1206935658983687

feat: migrate model

---

src/dbt/kipptaf/models/schoolmint/grow/staging/stg_schoolmint_grow__microgoals.sql

---
- https://app.asana.com/0/0/1206926364816753

feat: microgoals model

---

src/dbt/powerschool/models/base/base_powerschool__final_grades.sql
src/dbt/powerschool/models/staging/stg_powerschool__pgfinalgrades.sql

add citizenship and comment to final grades

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gpa_analysis.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__hs_early_warning_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__next_year_status.sql
src/dbt/powerschool/models/base/base_powerschool__student_enrollments.sql

feat: add next year status

---

src/dbt/kippcamden/dbt_project.yml
src/dbt/kippcamden/package-lock.yml
src/dbt/kippcamden/packages.yml
src/dbt/kippmiami/dbt_project.yml
src/dbt/kippmiami/package-lock.yml
src/dbt/kippmiami/packages.yml
src/dbt/kippnewark/dbt_project.yml
src/dbt/kippnewark/package-lock.yml
src/dbt/kippnewark/packages.yml
src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/package-lock.yml
src/dbt/kipptaf/packages.yml

Reverts TEAMSchools/teamster#831

Revert "feat: dbt dagster col metadata"

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__community_service.sql

add historical custom fields

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__community_service.sql

Hs cs update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__assessment_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

add Courage territory rosters to student filters

---

src/dbt/kipptaf/models/extracts/clever/rpt_clever__students.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql
src/dbt/kipptaf/models/students/intermediate/int_students__fldoe_fte.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: add union join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observation_details.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: use int internal id

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207004646721938

fix: use next term need to get

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__njsmart_transfer_unverified.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

To unverified update

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add fin aid fields to collab roster

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add academic year join

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fafsa criteria

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

actual college grad date

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207058745834272

add grad boolean to rem roster

---

src/teamster/core/deanslist/schema.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: rm doc

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__enrollment_pivot.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207080651266824

never enrolled

---

src/teamster/core/deanslist/assets.py
src/teamster/core/deanslist/schema.py
src/teamster/kipptaf/deanslist/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

checkout deanslist pydantic

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

only showing final scores on PM3 rows

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added a CTE to pre-filter QAF data so that pivot is not duped

---

src/teamster/kipptaf/google/forms/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: add form ids

---

src/dbt/powerschool/models/intermediate/int_powerschool__gradebook_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207124685100141

added scoretype to assignments table

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__nj_state_test_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

remove cognitive self contained exemption

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add hs grad date

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__student_info_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

edits_to_student_info_audit

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Added the counselor name from KFWD

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Ecc acceptances dash updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard_historic.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Act sat historic data first pass

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

hotfix for ea/ed acceptance calc

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

adding taf back

---

src/dbt/kipptaf/models/performance_management/sources.yml
src/dbt/kipptaf/models/performance_management/staging/stg_performance_management__leadership_development_metrics.sql
src/dbt/staging/packages.yml
src/dbt/teamster_utils/packages.yml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

942 add leadership development metrics as source table

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

update collab roster

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Add contact info to rem

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_taf_contact_feed.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Add ktc cohort to taf gsheet

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__nj_state_test_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add science DLM exemption

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add matric decision

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

update grad field

---

src/teamster/kipptaf/google/forms/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

ʇsɐǝq ǝɥʇ ɟo ɹǝqɯnu ǝɥʇ 999

---

src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/powerschool_enrollment/sources-external.yml
src/dbt/kipptaf/models/powerschool_enrollment/staging/stg_powerschool_enrollment__submission_records.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: dbt models

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Change mismatched data types to strings in alchemer results CTE
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

changing survey_id and response_id data type to string

---

src/dbt/kipptaf/models/pearson/sources-kippcamden.yml
src/dbt/kipptaf/models/pearson/sources-kippnewark.yml
src/dbt/kipptaf/models/pearson/staging/stg_pearson__student_list_report.sql
src/dbt/pearson/models/sources.yml
src/dbt/pearson/models/staging/stg_pearson__student_list_report.sql
src/teamster/core/iready/schema.py
src/teamster/core/pearson/schema.py
src/teamster/core/utils/functions.py
src/teamster/kippcamden/pearson/assets.py
src/teamster/kippnewark/pearson/assets.py
tests/assets/test_sftp_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

948 create table for pearson preliminary results for njsla njgpa

---

tests/assets/test_dbt_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

462 pass over auto materializing dbt views unless theres a new code version

---

src/teamster/core/google/storage/io_manager.py
src/teamster/kippmiami/fldoe/config/assets.yaml
src/teamster/kippmiami/fldoe/schema.py
tests/assets/test_sftp_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207346232487399

1026 bring florida eocbest exams into teamster

---

src/dbt/kipptaf/models/surveys/sources-drive.yml
src/dbt/kipptaf/models/surveys/staging/stg_surveys__scd_answer_crosswalk.sql
src/dbt/kipptaf/models/surveys/staging/stg_surveys__scd_question_crosswalk.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: scd sources

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__student_info_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207346708575166

distinct dupes

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql
src/dbt/kipptaf/models/students/intermediate/int_students__graduation_path_codes.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207346277708514

Retrofit psat10 data

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Psat10 early warning dash

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql
src/dbt/kipptaf/models/illuminate/intermediate/int_illuminate__psat_unpivot.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207348182612041

added_rn_highest_to_psat10

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

dedup grad requirements

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

new table for preelim scores + appending to current dash data source

---

src/dbt/kipptaf/models/students/intermediate/int_students__graduation_path_codes.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207353475750295

added rn = 1 to psat10

---

src/dbt/kipptaf/models/people/sources-drive.yml
src/dbt/kipptaf/models/people/staging/stg_people__miami_performance_criteria.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207362065951364

feat: add gsheet

---

src/dbt/kipptaf/models/powerschool/staging/stg_powerschool__storedgrades.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207364268687044

add if statement for transfer grades

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: leadership development assignments join on route

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

Remove columns we don't need and non-leader people.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

removing unused rows and columns

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Stat add alg i and civics

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed eoc and added science

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Add science fast

---

src/dbt/kipptaf/models/assessments/sources-drive.yml
src/dbt/kipptaf/models/assessments/staging/stg_assessments__assessment_expectations.sql
src/dbt/kipptaf/models/reporting/sources-drive.yml
src/dbt/kipptaf/models/reporting/staging/stg_reporting__gradebook_expectations.sql
src/teamster/kipptaf/amplify/dibels/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207395470532096

1064 please add to reporting g sheet views

---

.devcontainer/tpl/.env.tpl
pyproject.toml
src/teamster/kipptaf/dagster-cloud.yaml
src/teamster/kipptaf/resources.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: lilsis port config

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard_historic.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed ewbr

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippmiami_payout_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

correct admin window for STAR

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

Allow for edits to user participation from app table to determine which assignments are made.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

leadership development active user join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__promo_status.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add self-contained, DLM, and PS log exemption criteria

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix HS & report card issues

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_k2_star.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

update subject aliasing for STAR

---

src/dbt/iready/packages.yml
src/dbt/kippcamden/dbt_project.yml
src/dbt/kippcamden/packages.yml
src/dbt/kippmiami/dbt_project.yml
src/dbt/kippmiami/packages.yml
src/dbt/kippnewark/dbt_project.yml
src/dbt/kippnewark/packages.yml
src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/package-lock.yml
src/dbt/kipptaf/packages.yml
src/dbt/teamster_utils/packages.yml
src/teamster/core/resources.py
tests/assets/test_dbt_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: add dagster dbt column metadata

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added variable to change academic years on all locations

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

temporary change to build goals view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

putting things back

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

temp HS credit fix

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

adding ADSO title to match on specific leadership development metrics

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

removing filter

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add "live" cumulative GPA to FLC view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

matric type fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

Reverts TEAMSchools/teamster#1212

Revert "matric type fix"

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql

- [ x] <kbd>Format</kbd> has been run on all modified files
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207623514863263

Attrition updates

---

src/dbt/kipptaf/models/performance_management/sources-external.yml
src/dbt/kipptaf/models/performance_management/staging/stg_performance_management__observation_details_archive.sql
src/teamster/libraries/performance_management/schema.py
tests/assets/test_sftp_assets.py
tests/assets/test_sftp_pm_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Pm archive schema

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add filter for spring only

---

src/dbt/kippcamden/package-lock.yml
src/dbt/kippcamden/packages.yml
src/dbt/kippmiami/package-lock.yml
src/dbt/kippmiami/packages.yml
src/dbt/kippnewark/package-lock.yml
src/dbt/kippnewark/packages.yml
src/dbt/kipptaf/models/pearson/intermediate/int_pearson__all_assessments.sql
src/dbt/kipptaf/package-lock.yml
src/dbt/kipptaf/packages.yml
src/teamster/code_locations/kipptaf/dagster-cloud.yaml
src/teamster/libraries/dbt/assets.py
tests/assets/test_dbt_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: cut down columns to speed up column lineage post-hook

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add tier filters to STAT views

---

src/teamster/code_locations/kippcamden/datagun/schedules.py
src/teamster/code_locations/kippmiami/datagun/schedules.py
src/teamster/code_locations/kippnewark/datagun/schedules.py
src/teamster/code_locations/kipptaf/adp/workforce_now/api/schedules.py
src/teamster/code_locations/kipptaf/datagun/assets.py
src/teamster/code_locations/kipptaf/datagun/jobs.py
src/teamster/code_locations/kipptaf/datagun/schedules.py
src/teamster/code_locations/kipptaf/dbt/assets.py
src/teamster/code_locations/kipptaf/definitions.py
src/teamster/code_locations/kipptaf/fivetran/schedules.py
src/teamster/code_locations/kipptaf/google/directory/schedules.py
src/teamster/code_locations/kipptaf/ldap/schedules.py
src/teamster/code_locations/kipptaf/schoolmint/grow/schedules.py
tests/resources/test_adp_wfn_resource.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Sy25 scheduling

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

kept only active students

---

src/teamster/code_locations/kippcamden/titan/assets.py
src/teamster/code_locations/kippcamden/titan/config/assets.yaml
src/teamster/code_locations/kippcamden/titan/schema.py
src/teamster/code_locations/kippnewark/titan/assets.py
src/teamster/code_locations/kippnewark/titan/config/assets.yaml
src/teamster/code_locations/kippnewark/titan/schema.py
src/teamster/code_locations/kipptaf/dagster-cloud.yaml
src/teamster/libraries/titan/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

refactor: titan assets and schema

---

src/teamster/libraries/titan/sensors.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: ssh error handling

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__community_service_upload.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

create upload view for community service

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added fafsa field

---

src/teamster/code_locations/kipptaf/adp/workforce_now/sftp/sensors.py
src/teamster/code_locations/kipptaf/airbyte/sensors.py
src/teamster/code_locations/kipptaf/deanslist/sensors.py
src/teamster/code_locations/kipptaf/fivetran/sensors.py
src/teamster/code_locations/kipptaf/google/sheets/sensors.py
src/teamster/code_locations/kipptaf/ldap/sensors.py
src/teamster/code_locations/kipptaf/tableau/sensors.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

refactor: create asset jobs for sensors

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__leadership_development_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix: Add Fellow School Operations Director to Leadership Development auto-assignments.

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

laszlobela's tutoring filter

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__student_contact_info.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: boy status

---

src/dbt/kippmiami/models/fldoe/staging/stg_fldoe__fsa.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207857656810982

added iready moy to stat and fixed test_name on fsa

---

src/dbt/kippmiami/models/fldoe/staging/stg_fldoe__fsa.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207872486748517

Fix fsa on stat

---

src/teamster/code_locations/kipptaf/_google/sheets/sensors.py
src/teamster/libraries/adp/workforce_manager/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: exception handling

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

updated sy to include historic and current

---

src/dbt/kipptaf/models/adp/payroll/staging/stg_adp_payroll__general_ledger_file.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_preelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207909596891551

Add teacher number

---

.trunk/trunk.yaml
src/teamster/code_locations/kippcamden/powerschool/assets.py
src/teamster/code_locations/kippcamden/powerschool/sensors.py
src/teamster/code_locations/kippmiami/powerschool/assets.py
src/teamster/code_locations/kippmiami/powerschool/sensors.py
src/teamster/code_locations/kippnewark/powerschool/assets.py
src/teamster/code_locations/kippnewark/powerschool/sensors.py
src/teamster/libraries/powerschool/sis/assets.py
src/teamster/libraries/powerschool/sis/sensors.py
tests/assets/test_powerschool_sis_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

1229 powerschool sis sensor tables without incremental columns hash everything to compare changes

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add survey recon fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

OKRTS updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Rollover carat

---

src/dbt/kipptaf/models/assessments/intermediate/int_assessments__college_assessment_practice.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

removed academic year filter

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix dl roster issue

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add data quality metrics

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add calculated fiscal year

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__student_enrollments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added YYYY-YYYY

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed FSA name

---

src/dbt/kipptaf/models/extracts/rpt_appsheet__seat_tracker_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

adding special ed, teaching and learning, HR

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

re-added schedule student number so that % match amplify

---

src/teamster/code_locations/kipptaf/_google/bigquery/sensors.py
src/teamster/code_locations/kipptaf/definitions.py
src/teamster/code_locations/kipptaf/fivetran/__init__.py
src/teamster/code_locations/kipptaf/fivetran/sensors.py
src/teamster/libraries/fivetran/sensors.py
tests/sensors/test_fivetran_sensor.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: fivetran/bq sensor

---

src/dbt/kipptaf/models/google/appsheet/staging/stg_google_appsheet__illuminate_assessments_extension.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: create staging model

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_nj_prelim.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

retrofit int_tableau_enroll and fixed spelling for prelim

---

src/dbt/kipptaf/models/extracts/google/sheets/int_gsheets__dds_import.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__dds_import_classes.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__dds_import_students.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__dds_import_users.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208048738153080

feat: dds queries

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

CB2 SMG Add strand scores, Miami BOY

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__student_enrollments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added hr to stu enroll tab

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__powerschool_calendar_day.sql

Making a thing that will allow Nick to check the number of school days between two dates for each school
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

making a thing for Nick

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

removed deprecated cte

---

src/dbt/kipptaf/models/adp/workforce_now/intermediate/int_adp_workforce_now__worker.sql
src/dbt/kipptaf/models/adp/workforce_now/workers/staging/stg_adp_workforce_now__workers.sql
src/dbt/kipptaf/models/dayforce/base/base_dayforce__employee_history.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__intacct_integration_file.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_overall_scores.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__school_community_diagnostic.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_goals.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_job_salary_audit.sql
src/dbt/kipptaf/models/google/forms/base/base_google_forms__form_responses.sql
src/dbt/kipptaf/models/people/base/base_people__staff_roster_history.sql
src/dbt/kipptaf/models/people/intermediate/int_people__annual_historic_data.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__manager_survey_details.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__response_identifiers.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__support_survey_details.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__survey_responses.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208078350976679

fix: start and end dates

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__pm_assignment_roster.sql
src/dbt/kipptaf/models/extracts/rpt_appsheet__seat_tracker_roster.sql
src/dbt/kipptaf/models/extracts/rpt_schoolmint_grow__users.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_overall_scores.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__school_community_diagnostic.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_goals.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_roster.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_responses.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__teacher_development.sql
src/dbt/kipptaf/models/people/base/base_people__staff_roster_history.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__survey_responses.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

refactor: move teacher grade levels to reporting views

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

coalesce new state testing  exemption field

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add: new titles and miami goal calc

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_goals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Cb2 microgoals

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__teacher_development.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add: current year glows and grows

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__teacher_development.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

same thing

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__persistence.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208097893397089

coalesce grad progress denominators

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

app status added

---

src/dbt/kipptaf/models/amplify/intermediate/int_amplify__all_assessments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

do i get points for not using distinct?

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208126863759027

remove rn_year from WHERE clauses

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__designations.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add additional GPA designations

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

change join to create student-week scaffold

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

change source of date columns for okrts dashboard view

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add OG students table to kfwd roster view for audit purposes

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add additional tier calc criteria in case statement

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: adding status filter to leadership app roster

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

created 4yr ecc

---

src/dbt/overgrad/models/intermediate/int_overgrad__custom_fields_pivot.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208154898922218

add common app field to og custom field pivot

---

src/dbt/kipptaf/models/amplify/intermediate/int_amplify__all_assessments.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__reading_levels.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208136407966967

3 4 deandlist dibels

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add initial og data to kfwd dash view

---

src/dbt/powerschool/models/staging/stg_powerschool__assignmentscore.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: scorepoints

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208170794348757

fix missing Miami data

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Leadership development app

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attendance.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

date update for NJ

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

comment out prelim union for next yr

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix dupe row issue

---

src/dbt/kipptaf/models/amplify/intermediate/int_amplify__all_assessments.sql
src/dbt/kipptaf/models/amplify/staging/stg_amplify__benchmark_student_summary.sql
src/dbt/kipptaf/models/amplify/staging/stg_amplify__pm_student_summary.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208185592343383

Add grade level int to dibels

---

src/dbt/kipptaf/models/amplify/sources-drive.yml
src/dbt/kipptaf/models/amplify/staging/stg_amplify__dibels_pm_expectations.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: dibels expectations

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add is_current_week

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

change mastery calc to exclude NULLs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_gpa.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed if statement for gpa_term

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_gpa.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed union

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add n_wishlist to main select

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Kfwd dash og fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

changing completeness threshold for boy

---

src/dbt/kipptaf/models/extracts/clever/rpt_clever__sections.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__iready_lessons.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__sight_words.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__stipends_app_roster.sql
src/dbt/kipptaf/models/extracts/illuminate/rpt_illuminate__roles.sql
src/dbt/kipptaf/models/extracts/rpt_coupa__users.sql
src/dbt/kipptaf/models/extracts/rpt_egencia__users.sql
src/dbt/kipptaf/models/extracts/rpt_littlesis__enrollments.sql
src/dbt/kipptaf/models/extracts/rpt_schoolmint_grow__users.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attendance.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__suspension_over_time.sql
src/dbt/kipptaf/models/google/appsheet/intermediate/int_seat_tracker__snapshot.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__enrollment_pivot.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql
src/dbt/kipptaf/models/people/intermediate/int_people__annual_historic_data.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__teacher_assignment_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

style: replace calcs with template strings

---

src/dbt/kippmiami/models/fldoe/intermediate/int_fldoe__all_assessments.sql
src/dbt/kipptaf/models/extracts/clever/rpt_clever__sections.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql
src/dbt/kipptaf/models/extracts/illuminate/rpt_illuminate__mastschd.sql
src/dbt/kipptaf/models/extracts/illuminate/rpt_illuminate__terms.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__approved_home_instruction.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__power_standards.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__qbl.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__seat_tracker.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition_details.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_job_salary_audit.sql
src/dbt/kipptaf/models/kippadb/base/base_kippadb__application.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__contact_note_rollup.sql
src/dbt/kipptaf/models/surveys/intermediate/int_surveys__manager_survey_details.sql
src/dbt/powerschool/models/base/base_powerschool__student_enrollments.sql
src/dbt/teamster_utils/macros/date_diff_weekday.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

style: replace case with if

---

src/dbt/kipptaf/models/adp/payroll/properties.yml
src/dbt/kipptaf/models/adp/payroll/sources-external.yml
src/dbt/kipptaf/models/extracts/properties.yml
src/teamster/code_locations/kippcamden/_dbt/__init__.py
src/teamster/code_locations/kippcamden/definitions.py
src/teamster/code_locations/kippmiami/_dbt/__init__.py
src/teamster/code_locations/kippmiami/definitions.py
src/teamster/code_locations/kippnewark/_dbt/__init__.py
src/teamster/code_locations/kippnewark/definitions.py
src/teamster/code_locations/kipptaf/_dbt/__init__.py
src/teamster/code_locations/kipptaf/definitions.py
src/teamster/libraries/datagun/assets.py
src/teamster/libraries/dbt/asset_utils.py
src/teamster/libraries/dbt/dagster_dbt_translator.py
src/teamster/libraries/sftp/assets.py
src/teamster/libraries/tableau/assets.py

revert: retire dbt code version sched
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

refactor: AMP to automation condition

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__teacher_assignment_audit.sql
src/dbt/powerschool/models/intermediate/int_powerschool__assignment_score_rollup.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Add new fields

---

src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__teacher_assignment_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208324817844458

changed week range to mon to sun

---

src/dbt/pearson/models/staging/stg_pearson__njsla_science.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed labeling for performance level conversion.

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: changing name of PM coach form on join

---

src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__aptest.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208344875615620

added 2024

---

src/dbt/kipptaf/models/extracts/appsheet/rpt_appsheet__stipend_app_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208342179948218

fix: stipend app null and self approvers

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__student_assignment_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208345876105201

Add condition for assignments and null updated category

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_interventions.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

create CA intervention Tableau view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_interventions.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Chron abs log

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added null for 80% <2.0

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_interventions.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add addt'l commlog fields

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

one last time

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208049038599661

Parse field further

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_interventions.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add addt'l commlog columns

---

Dockerfile
pdm.lock
pyproject.toml
requirements.txt
src/teamster/code_locations/kipptaf/overgrad/assets.py
src/teamster/libraries/tableau/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

build(deps): python update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add: walkthrough track pivots

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add school name column to okrts

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

change CTE to reflect FAST subject name change

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix incentive exclusion

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add 2 years of diagnostics

---

.github/workflows/mkdocs-gh-deploy.yaml
docs/guides/dagster.md
mkdocs.yml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

docs: guide dagster tableau

---

src/dbt/kipptaf/models/illuminate/staging/stg_illuminate__aptest.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208422252923865

added rn and rn highest to aptest

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__student_enrollments.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_missing_assign_only.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Gradebook miss assign edits

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_missing_assign_only.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed dups

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

new BS asks, ms attended and postsec status

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix Miami social work category issue

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Okrts tree updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add new grad calcs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Kfwd grad update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_gpa.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__student_assignment_audit.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__teacher_assignment_audit.sql
src/dbt/powerschool/models/intermediate/int_powerschool__assignment_score_rollup.sql
src/dbt/powerschool/models/intermediate/int_powerschool__gradebook_assignments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Gradebook requests

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add incident type

---

src/dbt/powerschool/models/intermediate/int_powerschool__assignment_score_rollup.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fixed dcid

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__ddi_tier_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

remove Miami filter, add IEP

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

kinder promo fix

---

src/dbt/kipptaf/models/amplify/dibels/intermediate/int_amplify__all_assessments.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Pm goal addition

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

exclude WPP scope

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__student_assignment_audit.sql
src/dbt/powerschool/models/intermediate/int_powerschool__assignment_score_rollup.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Swap new scorepoints field

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

swapped scorepoints for converted

---

src/dbt/kipptaf/models/extracts/appsheet/rpt_appsheet__stipend_app_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

refactor: remove mdso route

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__star.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__state_test_scores.sql
src/dbt/kipptaf/models/renlearn/intermediate/int_renlearn__star_rollup.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

create Star, update state testing

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add distance to proficiency/growth calcs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added met standard goal vs met overall goal fields

---

.trunk/trunk.yaml
src/dbt/iready/models/staging/stg_iready__diagnostic_results.sql
src/teamster/libraries/iready/schema.py
src/teamster/libraries/sftp/assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix 20241008

---

src/dbt/kipptaf/models/amplify/dds/sources-external.yml
src/dbt/kipptaf/models/amplify/dibels/sources-drive.yml
src/dbt/kipptaf/models/amplify/dibels/staging/stg_amplify__dibels_goals_long.sql
src/dbt/kipptaf/models/amplify/dibels/staging/stg_amplify__dibels_goals_wide.sql
src/dbt/kipptaf/models/amplify/mclass/sources-external.yml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added fields for benchmarks

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added season as a field and join for comps

---

src/dbt/kipptaf/macros/utils.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__stipend_and_bonus_app.sql
src/dbt/kipptaf/models/google/appsheet/staging/stg_stipend_and_bonus__output.sql
src/dbt/kipptaf/snapshots/google/appsheet/snapshot__stipend_and_bonus__output.sql
src/dbt/kipptaf/snapshots/iready/snapshot_iready__instructional_usage_data.sql
src/dbt/kipptaf/snapshots/people/snapshot_people__employee_numbers.sql
src/dbt/kipptaf/snapshots/people/snapshot_people__staff_roster.sql
src/dbt/kipptaf/snapshots/people/snapshot_people__student_logins.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

feat: snapshot

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

remove OOD students

---

.trunk/trunk.yaml
src/dbt/kipptaf/models/extracts/appsheet/rpt_appsheet__seat_tracker_roster.sql
src/dbt/kipptaf/models/extracts/appsheet/rpt_appsheet__stipend_app_roster.sql
src/dbt/kipptaf/models/people/intermediate/int_people__leadership_crosswalk.sql

Add MDOs for school locations and to two downstream views.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208503341354471

add: MDOs to leadership crosswalk

---

src/teamster/code_locations/kippcamden/powerschool/config/assets-full.yaml
src/teamster/code_locations/kippmiami/powerschool/config/assets-full.yaml
src/teamster/code_locations/kippnewark/powerschool/config/assets-full.yaml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: add cr_prevschoolname

---

Dockerfile
pdm.lock
requirements.txt

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

build(python): deps

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added new benchmark fields

---

.trunk/trunk.yaml
src/dbt/kipptaf/models/extracts/rpt_schoolmint_grow__users.sql
src/teamster/libraries/edplan/schema.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: edplan schema, smg school

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added to bm

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added years in network

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql
src/dbt/kipptaf/models/fldoe/intermediate/int_fldoe__all_assessments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Miami updates

---

docs/guides/dagster.md
mkdocs.yml
src/dbt/kipptaf/models/illuminate/sources-illuminate_dna_repositories.yml
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_444.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_445.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_446.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_447.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_448.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_449.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_450.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_451.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_452.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_453.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_454.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_455.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_456.sql
src/dbt/kipptaf/models/illuminate/staging/repositories/stg_illuminate__repository_457.sql
src/teamster/code_locations/kipptaf/fivetran/config/illuminate.yaml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Feat fivetran add repos

---

.devcontainer/tpl/.env.tpl
.trunk/trunk.yaml
.vscode/settings.json
src/dbt/iready/models/staging/stg_iready__diagnostic_results.sql
src/teamster/libraries/iready/schema.py
tests/assets/sftp/test_assets_sftp_iready.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix 20241016

---

src/dbt/kipptaf/models/kippadb/qa/int_kippadb__qa_hs_enrollment_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

new file hs audit

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__student_contact_info.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add gifted to scif extract

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_gpa.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added py data

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql
src/dbt/kipptaf/models/iready/intermediate/int_iready__instruction_by_lesson_union.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Iready apm update

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__student_enrollments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

changed hr tag on int_tableau student enroll

---

Dockerfile
pdm.lock
requirements.txt

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

build(deps): python

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

change i-ready lesson source

---

.trunk/trunk.yaml
Dockerfile
pdm.lock
requirements.txt
src/teamster/libraries/schoolmint/grow/resources.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix 20241018

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Ddi proficiency filter

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_fast.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

DDI adds to FAST dash

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

align effort grade

---

.trunk/trunk.yaml
scripts/scrape_powerschool_docs.py
src/teamster/code_locations/kippnewark/deanslist/config/multi-partition-monthly-assets.yaml
src/teamster/code_locations/kipptaf/tableau/config/assets.yaml
src/teamster/libraries/fldoe/schema.py
src/teamster/libraries/ssh/resources.py
tests/assets/test_dbt_assets.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix 20241023

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Edit comments flag

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__star.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add discipline

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

mark as not ap for hs chart options

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added new fields

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

safe cast actualscoredentered

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_nj_es.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Safe cast audit

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__mod_standards_domains.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix rounding on mastery %s

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

remove union join clause temporarily

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix psat10 discipline

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Bucket fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_gpa.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added tracker for eoq timing

---

.trunk/trunk.yaml
src/dbt/kipptaf/models/extracts/google/directory/rpt_google_directory__users_import.sql
src/teamster/libraries/deanslist/resources.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Fix 20241104

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add string version of dibels composite

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Promo updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add additional custom restraint fields

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Add core Fs to DL promo extract

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

promo MS update

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

MS promo update

---

src/dbt/kipptaf/models/amplify/dibels/sources-drive.yml
src/dbt/kipptaf/models/assessments/sources-drive.yml
src/dbt/kipptaf/models/coupa/sources-drive.yml
src/dbt/kipptaf/models/egencia/sources-drive.yml
src/dbt/kipptaf/models/extracts/rpt_coupa__users.sql
src/dbt/kipptaf/models/extracts/rpt_egencia__users.sql
src/dbt/kipptaf/models/google/forms/sources-drive.yml
src/dbt/kipptaf/models/reporting/sources-drive.yml
src/dbt/kipptaf/models/surveys/sources-drive.yml

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208711156859211

2001 coupaegencia user feed updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard_historic.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added ms attended

---

src/teamster/core/io_managers/gcs.py
tests/io_managers/test_dagster_io_managers.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

2109 dagstergcsiomanager file write failure nukes existing data

---

src/dbt/kipptaf/models/adp/workforce_now/intermediate/int_adp_workforce_now__worker_person.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: use API primary indicator

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__gpa_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

create gpa gsheets view

---

src/dbt/kipptaf/models/amplify/dibels/intermediate/int_amplify__all_assessments.sql
src/dbt/kipptaf/models/amplify/mclass/staging/stg_amplify__pm_student_summary.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208748923931752

Max score pm dibels

---

src/dbt/kipptaf/models/amplify/dibels/intermediate/int_amplify__all_assessments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added client date on join to dedup rounds

---

src/dbt/kipptaf/models/amplify/dibels/intermediate/int_amplify__all_assessments.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208757582950299

split pm and bm

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__gpa_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

switch to y1 of current term only

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

adding sl and dso info to tableau_staff_roster

---

src/teamster/code_locations/kippnewark/deanslist/assets.py
src/teamster/core/io_managers/gcs.py
src/teamster/libraries/iready/schema.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: schema, resources

---

src/dbt/kipptaf/models/extracts/rpt_schoolmint_grow__users.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Beverly santos fix

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_rem_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

just adding most recent enrollment info

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_contact_notes.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add sw referral date to cn view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

changed end of quarter to -4

---

.devcontainer/scripts/postCreate.sh
.vscode/settings.json
src/dbt/kipptaf/models/adp/workforce_now/intermediate/int_adp_workforce_now__person_communication_pivot.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

fix: regex

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add continuing boolean

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Spi persistence

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql
src/dbt/kipptaf/models/kippadb/base/base_kippadb__application.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

add rn_application_school

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208885502777924

New round dibels pm

---

src/dbt/kipptaf/models/extracts/python/rpt_python__manager_pm_averages.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

Updating year (2023 and after only) and form name changes

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__seat_tracker_roster.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

adding cert manager permissions

---

src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__marketing_facebook_page.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__marketing_facebook_post.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__marketing_instagram_page.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__marketing_instagram_post.sql
src/dbt/kipptaf/models/facebook/pages/sources.yml
src/dbt/kipptaf/models/instagram/business/sources.yml
src/teamster/code_locations/kipptaf/fivetran/assets.py
src/teamster/code_locations/kipptaf/fivetran/schedules.py

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

chore: disable fivetran social media assets

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

updates to tableau view now

---

Dockerfile

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

build: dockerfile caching

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

added and is_quarter_end_date_range to remove from non eoq time

---

.github/workflows/dagster-cloud-deploy.yaml
.trunk/trunk.yaml
Dockerfile

- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan

build: add user cmd

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

add CTE to enrollments union, change persisting calc

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql

fix is_continuing_completing

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

add additional doc types

---

src/dbt/kippcamden/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kippnewark/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kipptaf/models/extracts/powerschool/rpt_powerschool__autocomm_students.sql
src/dbt/kipptaf/models/extracts/powerschool/rpt_powerschool__autocomm_students_iep.sql
src/dbt/kipptaf/models/extracts/powerschool/rpt_powerschool__autocomm_teachers.sql

2327 add student email to ps autocomm

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

add 2+ suspension metrics

---

.github/workflows/deploy-prod-kippcamden.yaml
.github/workflows/deploy-prod-kippmiami.yaml
.github/workflows/deploy-prod-kippnewark.yaml
.github/workflows/deploy-prod-kipptaf.yaml
scripts/dbt.py
scripts/json2py.py
scripts/uv-update.py
uv.lock

build: pyton deps

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__leadership_development_assignments.sql
src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__leadership_development_roster.sql

Create a roster with permission levels to replace the base roster view in the Leader PM App.

Add: Leader PM App Roster View

---

scripts/dbt.py
src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/extracts/clever/rpt_clever__students.sql
src/dbt/kipptaf/models/extracts/illuminate/rpt_illuminate__programs.sql
src/teamster/code_locations/kipptaf/extracts/assets.py
src/teamster/code_locations/kipptaf/extracts/config/clever.yaml
src/teamster/code_locations/kipptaf/extracts/config/deanslist-annual.yaml
src/teamster/code_locations/kipptaf/extracts/config/illuminate.yaml
src/teamster/libraries/extracts/assets.py
tests/assets/test_assets_extracts.py

2343 add lep and gt status to illuminate and clever

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_attrition.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__student_attrition_over_time.sql

refactor: replace util table with generate array

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_k2_star.sql

update STAR dash source

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard_historic.sql

dedup scores

---

src/dbt/kipptaf/models/extracts/clever/rpt_clever__students.sql
src/teamster/code_locations/kipptaf/extracts/config/clever.yaml

fix: rename gifted status

---

src/dbt/kipptaf/models/powerschool/base/base_powerschool__student_enrollments.sql
src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippmiami.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/powerschool/models/base/base_powerschool__student_enrollments.sql
src/dbt/powerschool/models/staging/stg_powerschool__s_nj_ren_x.sql

feat: use stg_powerschool__s_nj_ren_x for 504

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__leadership_development_roster.sql

adding emails, null editable field

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

co.lunch_status,

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql

adding two fields 
make things on tableau much much simpler.

adding links + assignment for Survey HQ

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_links.sql

changing name lookup to match reporting terms for ITR

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql

moving from UTC to New York time

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__community_service.sql

added lab's name for cs hour form

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql

adding rn=1 so that it only pulls the most recently completed surveys

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_nj_es.sql

change eoq to align with ms

---

src/dbt/deanslist/models/intermediate/int_deanslist__incidents__custom_fields__pivot.sql

add arrest field to custom field pivot

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

Crdc okrts update

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__reading_levels.sql

Dibels translations

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_responses.sql

revert: survey join did not work

---

src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/crdc/sources-drive.yml
src/dbt/kipptaf/models/crdc/staging/stg_crdc__sced_code_crosswalk.sql

feat: crdc crosswalk

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__promo_status.sql

add promo fields

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

adding region join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_responses.sql

Adding primary indicator

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_taf_contact_feed.sql

add state_studentnumber

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_contact_notes.sql

created school visits

---

uv.lock

build: update python deps

---

.trunk/trunk.yaml
src/dbt/kipptaf/models/extracts/google/directory/rpt_google_directory__admin_import.sql
src/dbt/kipptaf/models/extracts/google/directory/rpt_google_directory__users_import.sql
src/dbt/kipptaf/models/extracts/rpt_adp_workforce_now__worker_update.sql
src/teamster/code_locations/kipptaf/_google/directory/jobs.py
src/teamster/code_locations/kipptaf/adp/workforce_now/api/jobs.py
src/teamster/code_locations/kipptaf/schoolmint/grow/jobs.py
src/teamster/libraries/google/bigquery/ops.py
tests/ops/test_ops_bigquery.py
tests/ops/test_ops_directory.py
tests/ops/test_ops_schoolmint_grow.py

Fix 20250124

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

create new survey view

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Career launch new

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Add clean income field

---

.trunk/trunk.yaml
src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/coupa/sources-drive.yml
src/dbt/kipptaf/models/coupa/staging/stg_coupa__address_name_crosswalk.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__intacct_department_lookup.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__intacct_fund_lookup.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__intacct_location_lookup.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__intacct_program_lookup.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__school_name_crosswalk.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__school_name_lookup.sql
src/dbt/kipptaf/models/coupa/staging/stg_coupa__user_exceptions.sql
src/dbt/kipptaf/models/egencia/sources-drive.yml
src/dbt/kipptaf/models/egencia/staging/stg_egencia__travel_managers.sql
src/dbt/kipptaf/models/egencia/staging/stg_egencia__traveler_group_exceptions.sql
src/dbt/kipptaf/models/egencia/staging/stg_egencia__traveler_groups.sql
src/dbt/kipptaf/models/extracts/rpt_coupa__users.sql
src/dbt/kipptaf/models/extracts/rpt_egencia__users.sql

Fix 20250127

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Fix reconciliation CTEs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql

Remove NULL contact_id

---

src/dbt/kipptaf/models/google/appsheet/intermediate/int_seat_tracker__snapshot.sql
src/dbt/kipptaf/models/google/appsheet/staging/stg_leadership_development__output.sql
src/dbt/kipptaf/snapshots/google/appsheet/snapshot_leadership_development__output.sql
src/dbt/kipptaf/snapshots/google/appsheet/snapshot_seat_tracker__seats.sql
src/dbt/kipptaf/snapshots/google/appsheet/snapshot_stipend_and_bonus__output.sql
src/dbt/kipptaf/snapshots/iready/snapshot_iready__instructional_usage_data.sql

2395 create snapshot for src leadership development output

---

src/dbt/kipptaf/models/extracts/clever/rpt_clever__staff.sql

feat: add to filter list

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql

forgot some peeps and needed to split eoq_items for conduct code sigh

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_v2.sql

MUAHAHAHAAH

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_final_roster.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_v2.sql

I will die on this hill

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_assignments_teacher.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_final_roster.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_v2.sql

made changes to category (split)

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__star.sql
src/dbt/kipptaf/models/renlearn/intermediate/int_renlearn__star_rollup.sql

Star dl fix

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

School visit cte

---

.trunk/trunk.yaml
uv.lock

build: python deps

---

src/dbt/kipptaf/models/people/sources-drive.yml
src/dbt/kipptaf/models/people/staging/stg_people__renewal_approvers.sql

feat: Add src_people__renewal_approvers

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

---
- https://app.asana.com/0/0/1209283733126229

added two new fields to dash

---

src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__assignment_score_rollup.sql

added a count for nulls

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql

ignore the name of the branch. making v2 a table

---

src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

fix FAST CTE

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_v2.sql

dedup effort_grade

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__app_rollup.sql

---
- https://app.asana.com/0/0/1209284447028388

max ecc accepted

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

added field needed to support KMSA tracking of EOF

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

IF to CASE to preserve NULLs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/kippadb/base/base_kippadb__application.sql

Kmsa eof tracking

---

.trunk/trunk.yaml
uv.lock

Build dagster 1912

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

coalesce iready lessons

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

i-Ready exempt

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

added is_math_double_blocked

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__student_contact_info.sql

add sf contact id to student contact feed

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql

remove sai, add efc

---

src/teamster/code_locations/kippcamden/deanslist/config/multi-partition-fiscal-assets.yaml
src/teamster/code_locations/kippmiami/deanslist/config/multi-partition-fiscal-assets.yaml
src/teamster/code_locations/kippnewark/deanslist/config/multi-partition-fiscal-assets.yaml
tests/assets/test_assets_deanslist.py

---
- https://app.asana.com/0/0/1209447961907039

feat: add comm log params

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_spi.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql

bgp needed for spi

---

src/dbt/kipptaf/models/pearson/intermediate/int_pearson__all_assessments.sql

---
- https://app.asana.com/0/0/1209465782608819

added localstudentidentifier

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

changed join to remove unnecessary expected test rows

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__crdc_roster.sql

added section id and added new code for 8th grade alg

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__crdc_roster.sql

added pass/fail

---

src/dbt/kipptaf/models/schoolmint/grow/sources-external.yml

perf add biglake params

---

src/dbt/kipptaf/models/adp/workforce_now/api/intermediate/int_adp_workforce_now__workers.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql
src/dbt/kipptaf/models/people/intermediate/int_people__next_year_salary_projections.sql
src/dbt/kipptaf/models/people/intermediate/int_people__renewal_status.sql
src/dbt/kipptaf/models/people/intermediate/int_people__staff_roster_history.sql

---
- https://app.asana.com/0/0/1209500107408008

Adding Hourly Rate to the people data stack

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__crdc_roster.sql

fixed c504_only field

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__grad_calcs.sql

---
- https://app.asana.com/0/0/1209513965280426

add 6yr any rate

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

add staff upn

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

new custom goals for round 7

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit_v2.sql

remove weeks after today

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

---
- https://app.asana.com/0/0/1209529638964201

Ddi update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__suspension_over_time.sql

add terms to suspension YoY

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__suspension_over_time.sql

Suspension terms

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__grad_calcs.sql

Change 6yr any calc

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

---
- https://app.asana.com/0/0/1209528621904864

change source of bgp data

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql

---
- https://app.asana.com/0/0/1209601079564835

adding renewal doc to the tableau feed

---

.devcontainer/devcontainer.json
src/dbt/renlearn/models/properties/stg_renlearn__fast_star.yml
src/dbt/renlearn/models/sources.yml
src/teamster/code_locations/kippmiami/iready/assets.py
src/teamster/code_locations/kippnewark/iready/assets.py
tests/assets/sftp/test_assets_sftp_iready.py

Fix 20250307

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__smartrecruiters.sql

---
- https://app.asana.com/0/0/1209599638306327

add: subject preference unnest

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__iready_apm.sql

Add new iready column to apm

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_scaffold.sql

just put it back where you found it!

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__smartrecruiters.sql

removing reference from unnest

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_es_comments.sql

---
- https://app.asana.com/0/0/1209634678123100

effort grade

---

src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql

add growth booleans

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_scaffold.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql

---
- https://app.asana.com/0/0/1209644935069943

remove current week and forward

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

filtered out miami

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__graduation_requirements.sql

---
- https://app.asana.com/0/0/1209661716313319

forgot two other fields!

---

.devcontainer/scripts/postCreate.sh
.github/workflows/deploy-prod-kipptaf.yaml
.k8s/1password/items.yaml
src/dbt/kippcamden/profiles.yml
src/dbt/kippmiami/profiles.yml
src/dbt/kippnewark/profiles.yml
src/dbt/kipptaf/profiles.yml
src/teamster/code_locations/kippcamden/dagster-cloud.yaml
src/teamster/code_locations/kippmiami/dagster-cloud.yaml
src/teamster/code_locations/kippnewark/dagster-cloud.yaml
src/teamster/code_locations/kipptaf/_dlt/illuminate/assets.py
src/teamster/code_locations/kipptaf/_dlt/salesforce/assets.py
src/teamster/code_locations/kipptaf/_dlt/zendesk/assets.py
src/teamster/code_locations/kipptaf/dagster-cloud.yaml
src/teamster/libraries/dlt/illuminate/assets.py
src/teamster/libraries/dlt/salesforce/assets.py
src/teamster/libraries/dlt/zendesk/assets.py

chore: use oath for dbt profile

---

uv.lock

build: upgrade python deps

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard.sql

---
- https://app.asana.com/0/0/1209673759485158

removed academic year

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments.sql

swap kippadb roster for contact staging + user

---

src/dbt/kipptaf/models/reporting/sources-drive.yml
src/dbt/kipptaf/models/reporting/staging/stg_reporting__graduation_paths_combos.sql
src/dbt/kipptaf/models/students/intermediate/int_students__graduation_path_codes.sql

---
- https://app.asana.com/0/0/1209683863084763

added new option for false fafsa

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

fixed dates for ssds period 2 current year

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

fix attachments

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

Years in network

---

src/teamster/code_locations/kipptaf/tableau/config/assets.yaml

---
- https://app.asana.com/0/0/1209757932477736

Add new datasources for gradebook dash

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

---
- https://app.asana.com/0/0/1209776991784861

added historical to student_enrollments_subjects

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

---
- https://app.asana.com/0/0/1209599846324419

add additional argument to enroll status CASE

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__grad_plan_tracking.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__gpnode.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__grad_plan_progress_student.sql

---
- https://app.asana.com/0/0/1209792297764381

i did need the coalesce after all

---

.vscode/settings.json
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__tableau_usage.sql

Tableau-usage-primary-indicator

---

src/dbt/kipptaf/models/extracts/clever/rpt_clever__students.sql
src/dbt/powerschool/models/base/base_powerschool__student_enrollments.sql
src/dbt/powerschool/models/intermediate/int_powerschool__contacts.sql
src/dbt/powerschool/models/intermediate/int_powerschool__student_contacts.sql
src/dbt/powerschool/models/intermediate/int_powerschool__student_contacts_pivot.sql

fix: contact priority order

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__stipend_app_roster.sql

fix: adding KTAF operations to all access

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_es_comments.sql

added ms comments for miami

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__stipend_app_roster.sql

---
- https://app.asana.com/0/0/1209863775539603

add: fellow dso to stipend app permissions

---

src/dbt/kippmiami/dbt_project.yml
src/dbt/kipptaf/models/powerschool/sources-kippcamden.yml
src/dbt/kipptaf/models/powerschool/sources-kippnewark.yml
src/dbt/kipptaf/models/powerschool/staging/properties/stg_powerschool__gpprogresssubjectearned.yml
src/dbt/kipptaf/models/powerschool/staging/stg_powerschool__gpprogresssubjectearned.sql
src/dbt/powerschool/models/sources.yml
src/dbt/powerschool/models/staging/properties/stg_powerschool__gpprogresssubjectearned.yml
src/dbt/powerschool/models/staging/stg_powerschool__gpprogresssubjectearned.sql
src/teamster/code_locations/kippcamden/powerschool/config/assets-nonpartition.yaml
src/teamster/code_locations/kippnewark/powerschool/config/assets-nonpartition.yaml
tests/assets/test_assets_powerschool_sis.py

feat: add gpprogresssubjectearned

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

add: race/ethnicity to smg dashboard

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

wrong race field

---

src/dbt/kipptaf/models/assessments/intermediate/int_assessments__scaffold.sql
src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments.sql
src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql
src/dbt/kipptaf/models/illuminate/dlt/properties/stg_illuminate__public__students.yml
src/dbt/kipptaf/models/powerschool/base/base_powerschool__student_enrollments.sql

feat: add ids

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql

fix FL bucket 1

---

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__stipend_app_roster.sql

fix: adding school leaders to stipend roster

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

Fix new custom goals

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

urm of ecc school

---

.trunk/trunk.yaml
uv.lock

build: updte python deps

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql

adjusted bm goal calc

---

src/dbt/kipptaf/models/powerschool/base/base_powerschool__course_enrollments.sql

resolving issue 1903

---

src/teamster/code_locations/kipptaf/tableau/config/assets.yaml

survey dash: turn on hourly updates

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql

change join for student tier

---

src/dbt/kipptaf/models/powerschool/base/base_powerschool__student_enrollments.sql

Change fafsa source

---

.trunk/trunk.yaml
src/teamster/core/io_managers/gcs.py
src/teamster/core/utils/classes.py
src/teamster/libraries/dbt/dagster_dbt_translator.py
src/teamster/libraries/dlt/zendesk/pipeline/helpers/__init__.py

Fix dbt sources

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql

fix: removing TNTP and Gallup from tracking

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_links.sql

fix: sign on date

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql

update dibels most recent source

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

changed state id for student number on join for NJ

---

src/teamster/code_locations/kipptaf/tableau/config/assets.yaml

necessity
---
- https://app.asana.com/0/0/1209964754423282

added new source to assets yml

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_subjects.sql

change top join

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__pm_outlier_detection.sql

adding primary_indicator

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ddi_dashboard.sql

Ddi updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_ms_hs_comments.sql

remove HR credit type from gradebook comments for ms/hs

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

HS ADA updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

Reverts TEAMSchools/teamster#2642

Revert "HS ADA updates"

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__leadership_pm_reminders.sql

add: location and entity to leader pm reminders

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

HS ADA update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

ADA dash update

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

Hi to okrts

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_assignments_teacher.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_categories_teacher.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_scaffold.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_student_category_scaffold.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_student_scaffold.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/properties/int_tableau__gradebook_audit_categories_teacher.yml
src/dbt/kipptaf/models/extracts/tableau/intermediate/properties/int_tableau__gradebook_audit_section_week_scaffold.yml
src/dbt/kipptaf/models/extracts/tableau/intermediate/properties/int_tableau__gradebook_audit_section_week_student_category_scaffold.yml
src/dbt/kipptaf/models/extracts/tableau/intermediate/properties/int_tableau__gradebook_audit_section_week_student_scaffold.yml
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__gradebook_audit.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__assignment_score_rollup.sql

necessity
---
- https://app.asana.com/0/0/1210126586860410

Miami es gradebook audit changes

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql

necessity
---
- https://app.asana.com/0/0/1210130135411087

expanded union all

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_referrals.sql

Join DL users for approver name

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

The dashboard should be bigger, it needs more things.

---

src/dbt/kipptaf/models/assessments/staging/properties/stg_assessments__state_test_comparison.yml
uv.lock

fix: col in data contract

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql

swapping out special characters

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_assignments_student.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_assignments_teacher.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_categories_teacher.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_flags.sql
src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_scaffold.sql

necessity
---
- https://app.asana.com/0/0/1210201153780581

returned social studies

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql

Add dps to flc

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

fix: active title filters

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippmiami_payout_roster.sql

Miami payouts

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippmiami_payout_roster.sql

limit region

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__contact_note_rollup.sql

Contact note updates

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__school_community_diagnostic.sql

remove: filter on action_id (changes year to year)

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__ap_assessment_dashboard.sql
src/teamster/code_locations/kipptaf/tableau/config/assets.yaml

necessity
---
- https://app.asana.com/0/0/1210354326298049

coalesced fields to force values for cy courses prior to scores

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__standardized_test_unpivot.sql

necessity
---
- https://app.asana.com/0/0/1210343140658853

added SCI course discipline to act science

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippmiami_payout_roster.sql

Miami payouts star fix

---

src/dbt/kipptaf/models/students/intermediate/int_students__graduation_path_codes.sql

necessity
---
- https://app.asana.com/0/0/1210439117466938

changed njgpa season date

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_renewal_feed.sql

removing trailing ws

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__promo_status.sql
src/dbt/kipptaf/models/reporting/intermediate/int_reporting__promotional_status.sql

manual retentions

---

src/dbt/kipptaf/models/extracts/intermediate/properties/int_extracts__student_enrollments.yml

necessity
---
- https://app.asana.com/0/0/1210582580530109

removing commented out tests

---

src/dbt/kipptaf/models/assessments/staging/properties/stg_assessments__academic_goals.yml

Goals lookup changes

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__attendance_dashboard.sql

hs ada calc change

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__student_attrition_over_time.sql

create attrition over time view

---

src/dbt/kipptaf/models/adp/workforce_now/sftp/sources-external.yml
src/dbt/kipptaf/models/adp/workforce_now/sftp/staging/stg_adp_workforce_now__time_and_attendance.sql
src/dbt/kipptaf/models/extracts/adp/rpt_adp_workforce_now__data_bridge.sql
src/teamster/code_locations/kipptaf/adp/workforce_now/sftp/assets.py
src/teamster/code_locations/kipptaf/adp/workforce_now/sftp/schema.py
src/teamster/libraries/adp/workforce_now/sftp/schema.py

feat: time and att file

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard_cmo_comps.sql

how did this even build

---

scripts/dbt-sxs.py
src/dbt/kipptaf/models/adp/workforce_now/api/intermediate/int_adp_workforce_now__workers.sql
src/dbt/kipptaf/models/adp/workforce_now/api/intermediate/int_adp_workforce_now__workers__custom_fields__pivot.sql
src/dbt/kipptaf/models/adp/workforce_now/api/staging/stg_adp_workforce_now__workers__work_assignments.sql
src/dbt/kipptaf/models/extracts/adp/rpt_adp_workforce_now__data_bridge.sql
src/dbt/kipptaf/models/people/intermediate/int_people__staff_roster_history.sql
src/teamster/libraries/adp/workforce_now/api/schema.py
tests/assets/test_adp_wfn_assets.py
tests/resources/test_resource_adp_workforce_now.py

fix: add time and att to adp schema

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql

replace null with local student identifier

---

src/dbt/powerschool/models/staging/stg_powerschool__schools.sql

fix: high grade is 5 for sumner ES

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__leadership_pm_reminders.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

fix: column name change for downstream views

---

src/dbt/powerschool/models/intermediate/int_powerschool__gpa_cumulative.sql

Proj gpa add

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__student_contact_info.sql

add home language to scif

---

src/dbt/powerschool/models/intermediate/int_powerschool__gpa_cumulative.sql

add unweighted y1 projected

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippfwd_collab_roster.sql

better access to all listed contact

---

src/dbt/kippcamden/dbt_project.yml
src/dbt/kippmiami/dbt_project.yml
src/dbt/kippnewark/dbt_project.yml
src/dbt/kipptaf/dbt_project.yml
src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__leadership_development_assignments.sql
src/dbt/kipptaf/models/people/intermediate/int_people__renewal_status.sql
src/teamster/code_locations/kippmiami/iready/assets.py
src/teamster/code_locations/kippnewark/iready/assets.py
src/teamster/libraries/iready/assets.py

chore: update current year

---

src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__app_rollup.sql

necessity
---
- https://app.asana.com/0/0/1210920820127955

Quality bar calcs

---

src/dbt/kippmiami/dbt_project.yml
src/dbt/kippnewark/dbt_project.yml
src/teamster/code_locations/kippmiami/renlearn/assets.py
src/teamster/code_locations/kippmiami/renlearn/schema.py
src/teamster/code_locations/kippnewark/renlearn/assets.py
src/teamster/code_locations/kippnewark/renlearn/schema.py
tests/assets/sftp/test_assets_sftp_renlearn.py

chore: disable ar assets

---

src/dbt/kipptaf/models/topline/intermediate/int_topline__college_entrance_exams.sql

necessity
---
- https://app.asana.com/0/0/1210968520447147

create sat/act int view for topline

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__laptop_assignments.sql

create tech inventory view

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__laptop_assignments.sql

Tech roster

---

src/dbt/kipptaf/macros/generate_cube_query.sql
src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__designations.sql
src/teamster/code_locations/kipptaf/tableau/config/assets.yaml

removed order by

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql

necessity
---
- https://app.asana.com/0/0/1210991356258164

Amplify tweaks

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_roster.sql
src/dbt/kipptaf/models/people/intermediate/int_people__staff_roster_history.sql

Adding pensions to staff roster

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__staff_roster.sql
src/dbt/kipptaf/models/people/intermediate/int_people__staff_roster_history.sql

Reverts TEAMSchools/teamster#2825

Revert "Adding pensions to staff roster"

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__final_grades.sql
src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__category_grades_pivot.sql
src/dbt/powerschool/models/intermediate/int_powerschool__category_grades_pivot.sql
src/dbt/powerschool/models/intermediate/properties/int_powerschool__category_grades_pivot.yml

feat: add hw grade

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__leadership_development.sql

refactor: active status field

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql

fix: reports to column coming from history instead of current

---

src/dbt/kipptaf/models/extracts/deanslist/rpt_deanslist__iready_lessons.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__iready_lessons_weeks.sql

iready lessons updates

---

src/dbt/kipptaf/models/deanslist/api/intermediate/int_deanslist__behavior_incentive_by_term.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__okrts_behavior.sql

add progress to Q incentive

---

src/dbt/kipptaf/models/amplify/mclass/sftp/staging/properties/stg_amplify__mclass__sftp__benchmark_student_summary.yml
src/dbt/kipptaf/models/amplify/mclass/sftp/staging/stg_amplify__mclass__sftp__benchmark_student_summary.sql

necessity
---
- https://app.asana.com/0/0/1211143272499818

replaced student_primary_id_studentnumber on surrogate key and cast

---

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__state_assessments_demographic_comps.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__state_assessments_dashboard.sql
src/dbt/kipptaf/tests/test_incorrect_student_number_pearson.sql

necessity
---
- https://app.asana.com/0/0/1211164692174219

Njsla scores official

---

src/teamster/code_locations/kipptaf/level_data/grow/assets.py
src/teamster/code_locations/kipptaf/level_data/grow/schedules.py

refactor: combine observation/assignment sched

---

src/dbt/kipptaf/models/students/intermediate/int_students__attendance_interventions.sql

fix schoolid join

---

src/dbt/kipptaf/models/students/intermediate/int_students__attendance_interventions.sql

update call status for CA interventions

---

.trunk/trunk.yaml
uv.lock

build: updates

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments.sql

add `next_year_school` column

---

src/dbt/deanslist/models/intermediate/int_deanslist__incidents__custom_fields__pivot.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__home_instruction.sql

Home instruction

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql
src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql
src/dbt/kipptaf/models/powerschool/base/base_powerschool__student_enrollments.sql

KFwd grad year

---

src/dbt/kipptaf/models/exposures/google-sheets.yml

necessity
---
- https://app.asana.com/0/0/1211251097632380

added gpa roster exposure to yml

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__mtss_rti.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

tweak WHERE

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__seat_tracker.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

new live view because timeline is broken

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

add columns

---

src/dbt/kipptaf/models/students/intermediate/int_students__attendance_interventions.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

remove 6 absences cut

---

src/dbt/kipptaf/models/exposures/google-sheets.yml
src/dbt/kipptaf/models/extracts/google/sheets/properties/rpt_gsheets__dibels_pm_goal_setting.yml
src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__dibels_pm_goal_setting.sql
src/dbt/kipptaf/models/google/sheets/sources-drive.yml
src/dbt/kipptaf/models/google/sheets/staging/properties/stg_google_sheets__dibels_bm_goals.yml

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

Dibels pm goals

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

Academic goals

---

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kfwd_flc.sql
src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments.sql
src/dbt/kipptaf/models/extracts/intermediate/properties/int_extracts__student_enrollments.yml
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__college_assessment_dashboard_v3.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__crdc_roster.sql
src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_dashboard.sql
src/dbt/kipptaf/models/google/sheets/sources-drive.yml
src/dbt/kipptaf/models/google/sheets/staging/properties/stg_google_sheets__kippfwd_seasons.yml
src/dbt/kipptaf/models/kippadb/base/base_kippadb__contact.sql
src/dbt/kipptaf/models/kippadb/base/properties/base_kippadb__contact.yml
src/dbt/kipptaf/models/kippadb/intermediate/int_kippadb__roster.sql
src/dbt/kipptaf/models/kippadb/staging/properties/stg_kippadb__contact.yml
src/dbt/kipptaf/models/kippadb/staging/stg_kippadb__contact.sql
src/dbt/kipptaf/models/powerschool/base/base_powerschool__student_enrollments.sql
src/dbt/kipptaf/models/powerschool/base/properties/base_powerschool__student_enrollments.yml

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

added new field

---

src/dbt/kipptaf/models/students/intermediate/int_students__dibels_participation_roster.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

lower case data

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__topline_cascade_dashboard.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__dashboard_aggregations.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__seats_staffed_weekly_aggregations.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__student_metrics.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__student_retention_weekly_aggregations.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

week end column for topline

---

src/dbt/kipptaf/models/topline/intermediate/int_topline__student_retention_weekly_aggregations.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

swap attrition_year for academic_year

---

src/dbt/kipptaf/models/students/intermediate/int_students__retention_over_time.sql
src/dbt/kipptaf/models/topline/intermediate/int_topline__student_retention_weekly_aggregations.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

fix topline retention date scaffold 🤞🏻

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

fix Camden Bucket 3 K-2 reading

---

src/dbt/kipptaf/models/extracts/intermediate/int_extracts__student_enrollments_weeks.sql
src/dbt/kipptaf/models/extracts/intermediate/properties/int_extracts__student_enrollments.yml
src/dbt/kipptaf/models/extracts/intermediate/properties/int_extracts__student_enrollments_subjects_weeks.yml
src/dbt/kipptaf/models/extracts/intermediate/properties/int_extracts__student_enrollments_weeks.yml

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

enrollment weeks bini refactor

---

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql

models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …

safe_divide
