src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
Add final scores and final tiers as columns to the PM rows.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> hotfix: Pm final scores and exceptions

src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observation_details.sql
Instead of fix being applied to new observations it was being applied to old ones because of wrong > < sign.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> < should have been > for date in fix to score weighting.

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql, src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__observation_details.sql
Fix an inner join that's filtering out people whose observers are no longer active in SMG.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> hotfix: terminated observers being filtered out

src/dbt/kipptaf/models/performance_management/intermediate/int_performance_management__overall_scores.sql
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1207152478034278
=> fix: tier calculation for tier 4 started at 3.5 instead of 3.495

src/dbt/kipptaf/models/surveys/intermediate/int_surveys__manager_survey_details.sql
Fixing a dedupe error on the manager int view. previously the view was pulling only the most recently submitted manager survey response regardless of year/term. This fix will pull the most recently submitted by year/term.
We're motivated to fix it because it's broke.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> fixing the deduping error

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey_weights.sql
Add data from Google Forms for the KIPP Forward Career Launch Survey.
@anthonygwalters, @CGibson17, I also added Google Forms to the item weights table but I think you guys might not use it anymore since you're calculating in the same view, let me know if I can/should delete.
Also, since we're joining on email to alumni data in the main select statement, I don't actually think we need salesforce id in the alchemer part of that CTE either. 
-- | --
<br class="Apple-interchange-newline">
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
- [SqlFluff …
=> adding union to data from google forms

src/dbt/kipptaf/models/extracts/google/sheets/rpt_gsheets__kippmiami_payout_roster.sql
Changing the school from the abbreviation name to the full name. Full name matches more cleanly with the staff roster
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> the longer school name matches more cleanly with the staff roster

src/dbt/powerschool/models/staging/stg_powerschool__assignmentsection.sql
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> fix: coalesce scoreentrypoints types

src/dbt/kipptaf/models/extracts/rpt_schoolmint_grow__users.sql
Add Coach roles for those without school admin or teacher titles. Student Support and KIPP Forward department members coaching teachers were not being assigned roles and inactivated in SMG.
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> adding non-teacher and non-admin coaches

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_dashboard.sql, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__dibels_pm_dashboard.sql
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> removed probe fields and added a filter for non-tested grades in 2023

.trunk/trunk.yaml, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__miami_k2_iready.sql, src/dbt/kipptaf/models/iready/base/base_iready__diagnostic_results.sql, src/dbt/kipptaf/models/iready/intermediate/int_iready__domain_unpivot.sql, src/dbt/kipptaf/models/iready/intermediate/int_iready__instruction_by_lesson_union.sql, src/dbt/kipptaf/models/reporting/intermediate/int_reporting__student_filters.sql
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> fix: rm dataset joins for iready

.github/actionlint.yaml, .github/workflows/dagster-cloud-deploy.yaml
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> ci: use different runners

src/dbt/deanslist/models/staging/stg_deanslist__incidents.sql, src/dbt/deanslist/models/staging/stg_deanslist__incidents__attachments.sql, src/dbt/kipptaf/models/amplify/dds/sources-external.yml, src/dbt/kipptaf/models/amplify/dibels/sources-drive.yml, src/dbt/kipptaf/models/amplify/mclass/sources-external.yml, src/dbt/kipptaf/models/deanslist/sources-kippcamden.yml, src/dbt/kipptaf/models/deanslist/sources-kippmiami.yml, src/dbt/kipptaf/models/deanslist/sources-kippnewark.yml, src/dbt/kipptaf/models/deanslist/staging/stg_deanslist__incidents__attachments.sql, src/dbt/kipptaf/models/iready/sources-kippmiami.yml, src/dbt/kipptaf/models/iready/sources-kippnj.yml, src/dbt/kipptaf/models/iready/staging/stg_iready__instruction_by_lesson_pro.sql, src/teamster/code_locations/kippcamden/deanslist/assets.py, src/teamster/code_locations/kippnewark/deanslist/assets.py, src/teamster/core/resources.py, src/teamster/libraries/deanslist/assets.py, src/teamster/libraries/deanslist/resources.py, tests/assets/test_assets_deanslist.py
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
---
- https://app.asana.com/0/0/1208905924600387
=> feat: list to avro file

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__seat_tracker_roster.sql
Add region-wide permission level (2) for Directors in Operations whose location is a "Room"
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> adding view region permissions for Directors of Regional Ops

src/teamster/code_locations/kipptaf/tableau/config/assets.yaml
Add the Coaching Conversation Tool dashboard to the tableau assets and set a cron_schedule the same as the SchoolMint Grow Dashboard
- deanslist
- edplan
- iready
- pearson
- powerschool
- renlearn
- titan
=> activating coaching conversation tool and adding refreshes

src/dbt/pearson/models/staging/stg_pearson__njgpa.sql, src/dbt/pearson/models/staging/stg_pearson__njsla.sql
=> coalesce ml fields for Pearson

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__seat_tracker_roster.sql, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_responses.sql
surveys: fix join on dates to staff roster history
=> fix: shortname label and staff history dates

src/dbt/kipptaf/dbt_project.yml, src/teamster/code_locations/kipptaf/extracts/assets.py, src/teamster/code_locations/kipptaf/extracts/config/illuminate.yaml, src/teamster/libraries/extracts/assets.py, tests/assets/test_assets_extracts.py
=> refactor: retire use of extract

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_career_launch_survey.sql
=> add hs GPA bands

src/dbt/kipptaf/models/extracts/tableau/intermediate/int_tableau__gradebook_audit_section_week_student_scaffold.sql, src/dbt/kipptaf/models/powerschool/intermediate/int_powerschool__assignment_score_rollup.sql
=> added RHET to NJ ES comment check

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql, src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_links.sql
…ld assignments don't disappear
Survey rounds that were inactive were dropping off of the survey completion table. I changed the join from current date to match on all matching surveys and we'll do the filtering of links and terms on Tableau.
- …
=> fix: using is_current from reporting terms instead of joining on current date

.devcontainer/scripts/postCreate.sh, .devcontainer/tpl/gcloud_dagster_service_account.json.tpl, .devcontainer/tpl/gcloud_service_account_json.tpl, .k8s/1password/items.yaml, src/teamster/code_locations/kipptaf/dagster-cloud.yaml, src/teamster/code_locations/kipptaf/resources.py, src/teamster/libraries/google/directory/resources.py, src/teamster/libraries/google/drive/resources.py, src/teamster/libraries/google/forms/resources.py, src/teamster/libraries/google/sheets/resources.py, tests/assets/test_assets_google_directory.py, tests/resources/test_google_directory_resource.py, tests/sensors/test_sensors_google_forms.py, tests/sensors/test_sensors_google_sheets.py
---
- https://app.asana.com/0/0/1209657752323598
=> refactor: use default k8s service account for google API opps

src/dbt/powerschool/models/intermediate/int_powerschool__gradebook_assignments.sql
---
- https://app.asana.com/0/0/1209646931487608
=> added tracking for data entry timestamps

src/dbt/kipptaf/models/extracts/google/appsheet/rpt_appsheet__stipend_app_roster.sql
=> fix: removing ops restriction for directors level 2

src/dbt/kipptaf/models/extracts/surveys/rpt_extracts__survey_reminder.sql
=> fix: add distinct mail to survey reminders

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__survey_completion.sql
necessity
---
- https://app.asana.com/0/0/1210035844478410
=> fix: using survey_response_id for unique count

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
=> fix: using current name for all records

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__mtss_rti.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> mtss tableau view

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__seat_tracker_snapshot.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> fix: date spine for seat tracker all in one view

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> remove dev filters

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__academic_goals_rollup.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> Academic goals

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__kfwd_verification.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> Kfwd verification update

src/dbt/kipptaf/models/topline/intermediate/int_topline__seats_staffed_weekly_aggregations.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> fixed join on seats staffed agg

src/dbt/kipptaf/models/extracts/tableau/rpt_tableau__schoolmint_grow_observation_details.sql
models:
config:
enforced: true
- name: ...
data_type: ...
- ...
- ...
exposures:
owner:
depends_on:
- ...
meta:
dagster:
kinds:
- ... …
=> bad join. whoopsie
